Introduce onboarding wizard
Strategy11/another-wordpress-classifieds-plugin pull request #73
Opened 2024-11-13 10:58 UTC by shervElmi

This PR introduces a new "Onboarding Wizard" feature within the AWP Classified Plugin Admin Panel.

### Testing Instructions

#### First Method:

Activate the AWP Classified plugin from the WP Admin Plugins page. Please note that you will be redirected to the Onboarding Wizard page **only if this is your first time activating the plugin**. Otherwise, you can access it directly via the URL.

#### Second Method:

Directly access the Onboarding Wizard via the URL.
Example: `http://example.com/wp-admin/admin.php?page=awpcp-recipes-onboarding-wizard`

### Demo

![CleanShot 2024-11-19 at 18 03 31](https://github.com/user-attachments/assets/de6babc2-a6ef-4660-be06-d95d5f7ce5e0)

2024-11-19 16:08 UTC, shervElmi commented
Hi @sorinmarta,  

There’s an issue with the plugin’s activation process that is beyond the scope of this PR.  

I’ve added the onboarding-related activation code to `installer.php` as shown below:  

```PHP
public function activate() {
    $this->install_or_upgrade();

    update_option( 'awpcp-activated', true );

    if ( get_transient( AWPCP_OnboardingWizard::TRANSIENT_NAME ) !== 'no' ) {
        set_transient(
            AWPCP_OnboardingWizard::TRANSIENT_NAME,
            AWPCP_OnboardingWizard::TRANSIENT_VALUE,
            60
        );
    }
}
```

However, the activation hook is currently disabled in the plugin. I attempted to enable it by uncommenting the code below, but it caused a PHP fatal error. I also tried resolving the issue, but it falls outside the scope of this PR.  

Here’s the relevant code from `includes/class-awpcp.php`:  

```PHP
public function bootstrap() {
    $this->settings_manager = $this->container['SettingsManager'];
    $this->js = AWPCP_JavaScript::instance();

    awpcp_load_plugin_textdomain( AWPCP_FILE );

    // TODO: Fix activation hook
    // awpcp_register_activation_hook( AWPCP_FILE, array( $this->installer, 'activate' ) );
}
```

2024-11-19 16:10 UTC, shervElmi commented
Because of this issue, when activating the plugin, users are not redirected to the Onboarding Wizard page. We need to resolve this issue first so I can test my code and proceed with reviewing this PR.

2024-11-20 11:54 UTC, sorinmarta commented
@shervElmi 

That activation logic is a big mess that will require a lot of time to fix so for efficiency I think we should just register an activation hook that does what you need so you can proceed.

I pushed a commit that does that, so you can test now.

Let me know when its tested and confirmed so that I can review.

Thanks!

2024-11-21 10:27 UTC, shervElmi commented
Thanks for your work on the issue @sorinmarta. The PR is now ready for review.

2024-11-21 12:53 UTC, sorinmarta requested changes
Great work as always @shervElmi! I added a few small comments and questions. Mostly about code comments, not functionality.

I'll leave the decision to change them or not to you. But before merging we need to fix the CI issues.

Thanks!

2024-11-21 12:53 UTC, sorinmarta commented on functions.php
> +function awpcp_inline_svg( $path, $use_images = true, $echo = true ) {
The doc comment says that the function sanitizes the SVG content but I don't see any sanitization.

2024-11-21 12:53 UTC, sorinmarta commented on includes/admin/class-admin.php
> +     * Check for certain page in Formidable settings
We don't check in Formidable settings 😅

2024-11-21 12:53 UTC, sorinmarta commented on resources/js/onboarding-wizard/ui/setupInitialView.js
> + * Determines the initial step based on the current state, such as whether Formidable Pro is installed
AWPCP pro, not Formidable Pro. And same for the function above

2024-11-21 13:41 UTC, shervElmi commented
I'm happy with your positive feedback and truly appreciate it @sorinmarta. I have just addressed the issues with the comments.

2024-11-21 13:46 UTC, shervElmi commented
@sorinmarta, could you check the PHPStan errors? They don't seem to be related to this PR. I haven't reviewed them in detail, so it's possible that some may be relevant to this PR.

2024-11-21 14:34 UTC, sorinmarta approved these changes
Thanks @shervElmi! You are right, there were some issues with the PHPStan config we have. It's all good now so I'll get this merged soon.

Amazing work!

2024-11-21 15:01 UTC, merged